version: '3.8'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    image: maasmai/gx-compliance:v1.0.4
    command: npm run start:dev
    container_name: gx-compliance-server
    ports:
      - 3000:3000
    restart: 'unless-stopped'
    environment:
      BASE_URL: http://localhost:3000
  dev_server:
    image: node:16.14
    command: npm run start:dev
    container_name: gx-compliance-server-dev
    ports:
      - "3000:3000"
    volumes:
      - $PWD:/usr/src/app
    environment:
      BASE_URL: http://localhost:3000
    working_dir: /usr/src/app
    restart: unless-stopped
    tty: true
    stdin_open: true
