apiVersion: apps/v1
kind: Deployment
metadata:
  name: gx-compliance-server-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gx-compliance-server-development
  template:
    metadata:
      labels:
        app: gx-compliance-server-development
    spec:
      containers:
        - env:
            - name: jws_wrong
              valueFrom:
                secretKeyRef:
                  name: gx-compliance-secrets
                  key: JWS_WRONG
            - name: spki
              valueFrom:
                secretKeyRef:
                  name: gx-compliance-secrets
                  key: SPKI
            - name: privateKey
              valueFrom:
                secretKeyRef:
                  name: gx-compliance-secrets
                  key: PRIVATE_KEY
            - name: REGISTRY_URL
              value: https://registry.gaia-x.eu
            - name: BASE_URL
              value: 'https://compliance.gaia-x.eu'
          image: registry.gitlab.com/gaia-x/lab/compliance/gx-compliance:development
          imagePullPolicy: Always
          name: gx-compliance-server-development
          ports:
            - containerPort: 3000
              name: http-api
---
kind: Service
apiVersion: v1
metadata:
  name: gx-compliance-server-development
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
  selector:
    app: gx-compliance-server-development
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: gx-compliance-server
  namespace: gx-lab
spec:
  rules:
  - host: compliance.lab.gaia-x.eu
    http:
      paths:
      - backend:
          service:
            name: gx-compliance-server-development
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - compliance.lab.gaia-x.eu
    secretName: gx-compliance-server-tls-secret
