apiVersion: v1
kind: Service
metadata:
  name: gx-compliance-2206-main
  namespace: gx-lab
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-api
  selector:
    app: gx-compliance-2206-main
  type: LoadBalancer
