apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gx-compliance.fullname" . }}
  labels:
    {{- include "gx-compliance.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gx-compliance.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gx-compliance.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ include "gx-compliance.fullname" . | trunc 10 | trimSuffix "-"}}-http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ (first (first .Values.ingress.hosts).paths).path }}
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: {{ (first (first .Values.ingress.hosts).paths).path }}
              port: {{ .Values.service.port }}
          env:
            - name: REGISTRY_URL
              value: {{ .Values.urls.registry}}
            - name: BASE_URL
              {{- with (first .Values.ingress.hosts) }}
              value: "https://{{ .host }}/{{ (first .paths).path}}"
              {{- end}}
            - name: SD_STORAGE_BASE_URL
              value: {{ .Values.urls.storage}}
            - name: SD_STORAGE_API_KEY
              value: {{ .Values.storageApiKey }}
            - name: privateKey
              value: {{ .Values.privateKey }}
            - name: X509_CERTIFICATE
              value: {{ .Values.X509_CERTIFICATE }}
            - name: APP_PATH
              value: "{{ (first (first .Values.ingress.hosts).paths).path }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
